engines:
  duplication:
    enabled: true
    config:
      languages:
        python:
    exclude_fingerprints:
      - a275f60437f03dcf3e00bd5b243ba374
      - 586d53a59ed6ce09342fffebfcc40e25
      - 19573420a65a701256b250a3cc01d689
  fixme:
    enabled: true
    config:
      strings:
        - FIXME
        - TODO
  pep8:
    enabled: true
  radon:
    enabled: true
    config:
      threshold: "C"

ratings:
  paths:
    - "appi/**.py"
